# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2784576d4d41bbb0e55fbb2f2f6b6d5ade9f560bd4dfe0f71f8de919883bd32a4e6b4fb459c4456395d771459c1eb61e34e300c8414cf8563abbf462d0b4415f

test:
  secret_key_base: 18b708ab7cd7ce289b542e7758fd1da8d813254576a3afddab84044bb12c83f25b7dcd8c2a8506b188764b8b8f35d5aa5bfba89ee3110a1b6c06ce011b28e972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
